export { deleteUserRouteDefinition } from "./auth/user/deleteUser.route.js"
export { readUserRouteDefinition } from "./auth/user/readUser.route.js"
export { updateUserRouteDefinition } from "./auth/user/updateUser.route.js"

export { readUserSessionRouteDefinition } from "./auth/userSession/readUserSession.route.js"
export { signInRouteDefinition } from "./auth/userSession/signIn.route.js"
export { signOutRouteDefinition } from "./auth/userSession/signOut.route.js"
export { signUpRouteDefinition } from "./auth/userSession/signUp.route.js"

export { statusRouteDefinition } from "./public/status.route.js"
export { readPersonRouteDefinition } from "./public/person/readPerson.route.js"
export { readRoleRouteDefinition } from "./public/role/readRole.route.js"
export { readPoliticalPartyRouteDefinition } from "./public/politicalParty/readPoliticalParty.route.js"
export { searchPersonsRouteDefinition } from "./public/search/searchPersons.route.js"
export { searchFactsRouteDefinition } from "./public/search/searchFacts.route.js"
export { searchSourcesRouteDefinition } from "./public/search/searchSources.route.js"
export { lastAddedRouteDefinition } from "./public/lastAdded/lastAdded.route.js"

export { upsertPersonRouteDefinition } from "./admin/person/upsertPerson.route.js"
export { upsertRoleRouteDefinition } from "./admin/role/upsertRole.route.js"
export { upsertPersonRoleRouteDefinition } from "./admin/personRole/upsertPersonRole.route.js"
export { upsertPoliticalPartyRouteDefinition } from "./admin/politicalParty/upsertPoliticalParty.route.js"
export { upsertPersonPoliticalPartyRouteDefinition } from "./admin/personPoliticalParty/upsertPersonPoliticalParty.route.js"
export { upsertFactRouteDefinition } from "./admin/fact/upsertFact.route.js"
export { upsertPublisherRouteDefinition } from "./admin/publisher/upsertPublisher.route.js"
export { upsertSourceRouteDefinition } from "./admin/source/upsertSource.route.js"
